fn get_straight_patterns() -> Vec<[Value; 5]> {
    let mut result = Vec::new();
    result.push([
        Value::Ace,
        Value::Two,
        Value::Three,
        Value::Four,
        Value::Five,
    ]);
    result.push([
        Value::Two,
        Value::Three,
        Value::Four,
        Value::Five,
        Value::Six,
    ]);
    result.push([
        Value::Three,
        Value::Four,
        Value::Five,
        Value::Six,
        Value::Seven,
    ]);
    result.push([
        Value::Four,
        Value::Five,
        Value::Six,
        Value::Seven,
        Value::Eight,
    ]);
    result.push([
        Value::Five,
        Value::Six,
        Value::Seven,
        Value::Eight,
        Value::Nine,
    ]);
    result.push([
        Value::Six,
        Value::Seven,
        Value::Eight,
        Value::Nine,
        Value::Ten,
    ]);
    result.push([
        Value::Seven,
        Value::Eight,
        Value::Nine,
        Value::Ten,
        Value::Jack,
    ]);
    result.push([
        Value::Eight,
        Value::Nine,
        Value::Ten,
        Value::Jack,
        Value::Queen,
    ]);
    result.push([
        Value::Nine,
        Value::Ten,
        Value::Jack,
        Value::Queen,
        Value::King,
    ]);
    result.push([
        Value::Ten,
        Value::Jack,
        Value::Queen,
        Value::King,
        Value::Ace,
    ]);

    return result;
}
